<?php
$Model_SanPham = new Model_SanPham();
$PaRam = $_Param;
$DSTin = $Model_SanPham->DSSanPhamPTAn(1, 1000, $Tong);
//var_dump($DSTin);
?>
<div class="panel panel-default">
    <div class="panel-heading" style="padding-left: 10px; ">
        <i class="fa fa-list-ol"></i>
        Danh Sách Bài viết
    </div>
    <div id="ThongBao"></div>
    <div class="panel-body">
        <form action="<?php echo $Model_SanPham->getLinkXoaSanPham() ?>" method="POST" >
            <table class="table table-bordered table-hover" id="datatable">
                <thead>
                    <tr>
                        <th style="width: 20px" >Chọn</th>
                        <th>Ngày đăng</th>
                        <th style="width: 40px;" >STT</th>
                        <th>Tiêu Đề</th>
                        <th>Chủ Sản Phẩm</th>
                        <th>Số Điện Thoại</th>
                        <th style="width: 100px;text-align: center;" >Vị Trị</th>
                        <th style="width: 100px;text-align: center;" >Giá</th>
                        <th style="width: 100px;text-align: center;" >Ẩn Hiện</th>
                        <th style="text-align: center;" >Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    
                    if ($DSTin) {
                        $Dem = 1;
                        foreach ($DSTin as $TinTuc) {
                            $_TinTuc = new Model_SanPham($TinTuc);
                            
                            ?>   
                            <tr>
                                <td><label style="display: block;"><input class="checkbox1" name="Chon[<?php echo $_TinTuc->MaSP ?>]" type="checkbox" value="<?php echo $_TinTuc->MaSP; ?>" ></label> </td>
                                <td><?php echo date("Y-m-d", strtotime($_TinTuc->NgayDang));  ?></td>
                                <td style="text-align: center;" ><?php echo $Dem++; ?></td>
                                <td><?php echo $_TinTuc->TenSP ?></td>
                                <td><?php echo $_TinTuc->NguoiLienHe ?></td>
                                <td><?php echo $_TinTuc->DienThoai ?></td>
                                <td><?php echo $_TinTuc->getNameViTri($_TinTuc->TinNoiBat); ?></td>
                                <td><?php echo $_TinTuc->GiaVND ?></td>
                                <td style="text-align: center;">
                                    <?php echo $_TinTuc->AnHien == FALSE ? "Ẩn" : "Hiện" ?>
                                </td>
                                <td style="width: 150px;text-align: center;">
                                    <div class="btn-group">
                                        <a class="btn btn-success" href="/quantrisanpham/quantrisanphamhientin/<?php echo $_TinTuc->MaSP; ?>"><i class="fa fa-check"></i></a>
                                        <a class="btn btn-success" href="<?php echo $Model_SanPham->getLinkSuaSanPham() . $_TinTuc->MaSP; ?>"><i class="fa fa-edit"></i></a>
                                        <a class="btn btn-danger xoa" href="<?php echo $Model_SanPham->getLinkXoaSanPham() . $_TinTuc->MaSP; ?>"><i class="fa fa-close"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <?php
                        }
                    }
                    ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th>Chọn</th>
                        <th>Ngày Đăng</th>
                        <th>STT</th>
                        <th>Tiêu Đề</th>
                        <th>Chủ Sản Phẩm</th>
                        <th>Số Điện Thoại</th>
                        <th style="text-align: center;" >Vị Trí</th>
                        <th style="text-align: center;" >Giá</th>
                        <th>Ẩn Hiện</th>
                        <th style="text-align: center;" >Action</th>
                    </tr>
                </tfoot>
            </table>
            <input name="XoaChon" class="xoa"  value="Xóa Mục Đang Chọn" type="submit" >

        </form>
    </div>
</div>
