<?php
$View_Layout = new View_layout();
$View_quancaoview = new View_quancaoview();
ob_start();
?>
<!DOCTYPE HTML>
<html>
    <head>
        <?php $View_Layout->layouthead(); ?>        
    </head>
    <body>
        <?php
        $View_Layout->layoutMenuCom($_Controller,$_Param);
        ?>
        <div class="container" >
            <div class="row" >
                <?php
                include $Conten;
                ?>
            </div>
        </div>
        <?php
        $View_Layout->layoutLienHe();
        $View_Layout->LayoutCopyright();
        ?>
        <script src="<?php echo BASE_DIR ?>public/home/js/bootstrap.js"></script>
        <script src="<?php echo BASE_DIR ?>public/home/js/owl.carousel.min.js" type="text/javascript"></script>
        <script>
            $(document).ready(function () {
//                window.oncontextmenu = new Function("return false;");
            });

            $('#link').click(function () {
                $("html, body").animate({scrollTop: 0}, 600);
                return false;
            });
        </script>
    </body>
</html>


<?php
$str = ob_get_clean();
$Model_Option = new Model_Option();
$DSOption = $Model_Option->DSOption();
foreach ($DSOption as $option) {
    $_Option = new Model_Option($option);
    $str = str_replace("{{$_Option->MaOption}}", $_Option->GiaTri, $str);
}
echo $str;
?>