<?php
$Model_QuangTri = new Model_QuanTri();
$NVHienTai = $Model_QuangTri->NhanVienHienTai();
$DSQuanTri = $Model_QuangTri->DSNhanVien();
?>
<div class="panel panel-default" >
    <div class="panel-body" >
        <div class=""  >
            <form action="<?php echo BASE_DIR ?>quantriuser/" method="POST" >
                <div class="panel panel-default" >
                    <div class="panel-heading" >
                        <h3 class="panel-title" >Thêm Nhân Viên</h3>
                    </div>
                    <div class="panel-body" > 
                        <div class="col-lg-4 col-md-4 " >
                            <div class="form-group" >
                                Username
                                <input required="required" name="username" class="form-control" >
                            </div>
                            <div class="form-group" >
                                Password
                                <input required="required" name="password"  type="text" class="form-control" >
                            </div>
                            <div class="form-group" >
                                Nhóm
                                <?php
                                echo $NVHienTai['Nhom'];
                                ?>
                                <select name="Nhom" required="required" class="form-control"  >
                                    <?php
                                    $ListNhom = $Model_QuangTri->getListNhom();
                                    foreach ($ListNhom as $k => $Nhom) {
                                        if ($k > $NVHienTai['Nhom']) {
                                            ?>
                                            <option   value="<?php echo $k ?>" ><?php echo $Nhom ?></option>
                                            <?php
                                        }
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 " >
                            <div class="form-group" >
                                Họ Tên
                                <input name="HoTen" required="required" class="form-control" >
                            </div>
                            <div class="form-group" >
                                Địa Chỉ
                                <textarea name="DiaChi" required="required"  class="form-control" ></textarea>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 " >
                            <div class="form-group" >
                                Email
                                <input name="email" required="required"  class="form-control" >
                            </div>
                            <div class="form-group" >
                                Số Điện Thoại
                                <input name="SDT" required="required"  type="text" class="form-control" >
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 text-center "  >
                            <div class=" form-group" >
                                <input name="Them" type="submit" value="Thêm usename" class="btn btn-primary" >
                            </div>

                        </div>
                    </div>
                </div>
            </form>


        </div>
        <div class="clearfix"  ></div>
        <div class="panel panel-default" >  
            <div class="panel-heading" >
                <h3 class="panel-title" >
                    Danh Sách Nhân Viên
                </h3>
            </div>

            <div class="panel-body table-responsive" >
                <table id="datatable" class="table table-bordered"  >
                    <thead>
                        <tr>
                            <td>username</td>
                            <td>Họ Tên</td>
                            <td>Đia Chỉ</td>
                            <td>SDT</td>
                            <td>Nhóm</td>
                            <td>Action</td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($DSQuanTri as $NhanVien) {
                            $_NhanVien = new Model_QuanTri($NhanVien);
                            ?>
                            <tr>
                                <td><?php echo $NhanVien['username'] ?></td>
                                <td><?php echo $NhanVien['HoTen'] ?></td>
                                <td><?php echo $NhanVien['DiaChi'] ?></td>
                                <td><?php echo $NhanVien['SDT'] ?></td>
                                <td><?php echo $_NhanVien->TenNhom ?></td>
                                <td>
                                    <?php
                                    if ($NhanVien['Nhom'] > 1) {
                                        ?>
                                        <a href="<?php echo BASE_DIR ?>quantriuser/xoanhanvien/<?php echo $NhanVien['username'] ?>" class="xoa btn btn-danger" >Xóa</a>
                                        <?php
                                    }
                                    ?>
                                    <a href="<?php echo BASE_DIR ?>quantriuser/xemnhanvien/<?php echo $NhanVien['username'] ?>" class="btn btn-success" >Xem</a>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td>username</td>
                            <td>Họ Tên</td>
                            <td>Đia Chỉ</td>
                            <td>SDT</td>
                            <td>Nhóm</td>
                            <td>Action</td>
                        </tr>
                    </tfoot>

                </table>
            </div>
        </div>
    </div>


</div>

