<?php
$Model_Option = new Model_Option();
$DSOption = $Model_Option->DSOption();
foreach ($DSOption as $option) {
    $_option = new Model_Option($option);
    define($_option->MaOption, $_option->GiaTri);
}
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>AdminLTE 2 | Dashboard</title>
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <link href="<?php echo BASE_DIR ?>public/mobie/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo BASE_DIR ?>public/mobie/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo BASE_DIR ?>public/mobie/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo BASE_DIR ?>public/mobie/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo BASE_DIR ?>public/mobie/style.css" rel="stylesheet" type="text/css" />
    </head>
    <body class="skin-blue sidebar-mini">
        <div class="wrapper">
            <header class="main-header" style="background-color: #fff;" >
                <a href="<?php echo BASE_DIR ?>mobie/" style="text-align: center;display: block;" >
                    <img srcset="<?php echo Option_Logo ?>" style="margin: auto;" >
                </a>
                <nav class="navbar navbar-static-top" role="navigation">
                    <div class="navbar-custom-menu" style="width: 100%;" > 
                        <ul class="nav navbar-nav menu_chinh " style="width: 100%;" >
                            <li >
                                <a href="<?php echo BASE_DIR ?>mobie/" class="text-center"> 
                                    <i class="fa fa-home" ></i> 
                                    <br>
                                    Trang Chủ
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo BASE_DIR ?>mobie/" class="text-center"> 
                                    <i class="fa fa-edit" ></i> 
                                    <br>
                                    Giới Thiệu
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo BASE_DIR ?>mobie/" class="text-center"> 
                                    <i class="fa fa-edit" ></i> 
                                    <br>
                                    Liên Hệ
                                </a>
                            </li>
                           
                            <li style="float: right" >
                                <a href="#" class="text-center"  data-toggle="offcanvas" role="button"> 
                                    <i class="fa fa-list" ></i> 
                                    <br>
                                    Mở Rộng
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
                <div class="clearfix"></div>
            </header>
            <aside class="main-sidebar" style="z-index: 9999;padding-top:0px;" >
                <section class="sidebar" style=" " >
                    <a href="<?php echo BASE_DIR ?>mobie/" style="text-align: center;display: block;padding-top: 10px;" >
                        <img srcset="<?php echo Option_Logo ?>" style="margin: auto;width: 90%;background-color: #fff;" >
                    </a>
                    <form action="#" method="get" class="sidebar-form">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Tìm Kiếm" />
                            <span class="input-group-btn">
                                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </form>
                    <ul class="sidebar-menu">
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-table"></i> <span>Tables</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="../tables/simple.html"><i class="fa fa-circle-o"></i> Simple tables</a></li>
                                <li><a href="../tables/data.html"><i class="fa fa-circle-o"></i> Data tables</a></li>
                            </ul>
                        </li>

                    </ul>
                </section>
            </aside>
            <div class="clearfix"></div>
            <div class="content-wrapper" style="padding-top: 10px;" >
                <?php 
                include $_NoiDungChinh;
                ?>
            </div>

            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 2.2.0
                </div>
                <strong>Copyright &copy; 2014-2015 <a href="#">Almsaeed Studio</a>.</strong> All rights reserved.
            </footer>
        </div>
        <script src="<?php echo BASE_DIR ?>public/mobie/jquery.js" type="text/javascript"></script>
        <script src="<?php echo BASE_DIR ?>public/mobie/plugins/jQuery/jQuery-2.1.4.min.js" type="text/javascript"></script>
        <script src="<?php echo BASE_DIR ?>public/mobie/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="<?php echo BASE_DIR ?>public/mobie/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="<?php echo BASE_DIR ?>public/mobie/plugins/fastclick/fastclick.min.js" type="text/javascript"></script>
        <script src="<?php echo BASE_DIR ?>public/mobie/dist/js/app.min.js" type="text/javascript"></script>
        <script src="<?php echo BASE_DIR ?>public/mobie/dist/js/demo.js" type="text/javascript"></script>
    </body>
</html>
