<?php
$Model_Option = new Model_Option();
$DSOption = $Model_Option->DSOption();
foreach ($DSOption as $option) {
    $_option = new Model_Option($option);
    define($_option->MaOption, $_option->GiaTri);
}
ob_start();
?>
<!DOCTYPE HTML>
<html>
    <head>
        <title>{Title}</title>
        <link rel="icon" href="{Icon}" >
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
        <meta name="keywords" content="{keywords}" />
        <meta name="description" content="{description}">
        <meta name="author" content="namdong92@gmail.com">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="<?php echo BASE_DIR ?>public/home/css/bootstrap.min.css">
        <link href="<?php echo BASE_DIR ?>public/home/css/font-awesome.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo BASE_DIR ?>public/home/css/owl.carousel.min.css" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="<?php echo BASE_DIR ?>public/home/css/style.css">
        <script src="<?php echo BASE_DIR ?>public/home/js/jquery-1.11.3.min.js"></script> 
    </head>
    <body>
        <?php
        View_layout::layoutMenuSangQuan();
        ?>
        <div class="container" >
            <div class="row" >
                <div class="panel panel-default" style="border-color: #fff; " >
                    <div class="panel-body" style="padding-top: 0px; " >
                        <div class="row" >
                            <div class="col-lg-8 col-md-8" >
                                <div class="row" >
                                    <?php
                                    include $Conten;
                                    ?>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4" >
                                <?php
                                include __DIR__ . '/../../layout/template/left.php';
                                ?>
                            </div>
                        </div>
                        <?php
//                        include __DIR__ . '/../../layout/template/footer.php';
                        include 'winget/danhmuclienquan.php';
                        ?>
                    </div>
                </div>
            </div>
        </div>
        <?php
        $View_Layout = new View_layout();
        $View_Layout->layoutLienHe();
        $View_Layout->LayoutCopyright();
        ?>
        <script src="<?php echo BASE_DIR ?>public/home/js/bootstrap.js"></script>
        <script src="<?php echo BASE_DIR ?>public/home/js/owl.carousel.min.js" type="text/javascript"></script>
        <script>
            $(document).ready(function () {
                window.oncontextmenu = new Function("return false;");
            });
            $('#link').click(function () {
                $("html, body").animate({scrollTop: 0}, 600);
                return false;
            });
        </script>
    </body>
</html>
<?php
include __DIR__ . '/../../layout/dinhnghia.php';
?>