<?php
$Model_Pages = new Model_Pages();
$Model_Tintuc = new Model_TinTuc();
$Page = new Model_Pages($Model_Pages->TimPages($data['page']));


?>
<ol class="breadcrumb">
    <li>
        <a href="<?php echo BASE_DIR ?>">Trang Chủ</a>
    </li>
    <li class="active"><?php echo $Page->TieuDe ?></li>
</ol>
<div style="padding-right: 15px;" >
    <?php
    $SL = 21;
    $pageht = $_Param[0];
    $pageht = intval($pageht);
    $pageht = $pageht > 1 ? $pageht : 1;
    $Model_Tintuc = new Model_TinTuc();
    $DSSanPham = $Model_Tintuc->DSTinTucLoaiPT1(1, $SL, $Page->Pagesid, $TongSanPham);
    if ($DSSanPham)
        foreach ($DSSanPham as $SanPham) {
            $_TinTuc = new Model_TinTuc($SanPham);
            ?>    
            <div class="col-lg-4 col-md-4 "  >
                <div class="thumbnail" >
                    <div class="SanPhamHinh" >
                        <img src="<?php echo $_TinTuc->UrlHinh; ?>" style="width: 100%;height: 180px;" alt="<?php echo $_TinTuc->TieuDe ?>"/>
                    </div>
                    <h3 class="text-center SanPhamTen" >
                        <a href="<?php echo $_TinTuc->LinkChiTiet ?>" >
                            <?php
                            if (strlen($_TinTuc->TieuDe) > 60) {
                                echo substr($_TinTuc->TieuDe, 0, 62) . "...";
                            } else {
                                echo $_TinTuc->TieuDe;
                            }
                            ?>
                        </a>
                    </h3>
                </div>
            </div>
            <?php
        }
    ?>
    <div class="col-lg-12 col-md-12" >
        <?php
        $TongTrang = ceil($TongSanPham/ $SL);
        echo $Model_Tintuc->PhanTrang($TongTrang, $pageht, BASE_DIR . 'index/[i]');
        ?>
    </div>
    <div class="clearfix" ></div>
</div>
