<div class="col-lg-8 col-md-10" style="display: table;margin: auto;float: none;" >
    <div style="border: 1px solid #0f76bf;margin-top: 20px;text-align: center;border-radius: 5px; " >
        <img style="margin: auto;margin-top: 20px;" src="<?php echo BASE_DIR ?>public/home/img/dichvu.png" alt="Dich  Vu"/>
        <div style="text-align: left;margin-left: 180px;" >
            <p><img src="<?php echo BASE_DIR ?>public/home/img/tick.png" alt=""/> Tin của quý khách sẽ được đăng trên chuỗi hệ thống Website:<br>
                <img style="margin-left: 30px" src="<?php echo BASE_DIR ?>public/home/img/logotrang.png" alt=""/>
            </p>
            <p><img src="<?php echo BASE_DIR ?>public/home/img/tick.png" alt=""/>Tin của quý khách sẽ được quảng cáo hiệu quả nhất.  </p>
            <p><img src="<?php echo BASE_DIR ?>public/home/img/tick.png" alt=""/>Tin của quý khách sẽ được đăng đến khi thành công.   </p>
            <p><img src="<?php echo BASE_DIR ?>public/home/img/tick.png" alt=""/>rất nhiều quán đã sang nhượng thành công trên <a href="#"  >sanhnhanh24h.com</a>   </p>
        </div>
        <a class="btn btn-danger" href="<?php echo BASE_DIR ?>dangtin/index/1" style="color: red;background-color: #fff;margin-bottom: 20px;" >Tiếp Tục</a>
    </div>
</div>
