<div class="panel panel-success">   
   <div class="panel-heading">
      <h3 class="panel-title">Thêm Tùy Chọn</h3>
   </div>
   <div class="panel-body">
       <form action="" method="POST">
         <table class="table table-bordered">
            <tr>
               <td>Tên chi nhánh</td>
               <td><input type='text' name="GiaTriVN" required="required" class="form-control"  ></td>
            </tr>
            <tr>
               <td>SDT</td>
               <td><input type='text' name="GhiChu[SDT]" required="required" class="form-control"  ></td>
            </tr>
            <tr>
               <td>Địa Chỉ</td>
               <td><input type='text' name="GhiChu[DiaChi]" required="required" class="form-control"  ></td>
            </tr>
         </table>
         <input class="btn-sm btn-success " name="Them" type="submit" value="Thêm Option">
      </form>
   </div>
</div>
