<h3 class="text-center" style="color: #0f76bf;padding: 30px;" >SANGNHANH24h.COM</h3>
<div class="container" >
    <div class="col-lg-6 col-md-6 text-center" >
        <h3 style="padding: 30px;border-radius: 100%;border: 5px solid #0f76bf;width: 200px;height: 200px;line-height: 120px;font-size: 80px;margin: auto;color: #0f76bf;  " >1</h3>
        <p style="font-size: 16px; color: #0f76bf;font-weight: bold;" >{DangTrucTiep}</p>
        <a class="btn btn-primary" style="background-color: #fff;color: #0f76bf;padding: 10px 50px" href="<?php echo BASE_DIR ?>taikhoan/buoc2" >Đăng tin ngay</a>
    </div>
    <div class="col-lg-6 col-md-6 text-center" >
        <h3 style="padding: 30px;border-radius: 100%;border: 5px solid red;width: 200px;height: 200px;line-height: 120px;font-size: 80px;margin: auto;color: red;  " >2</h3>
        <p style="font-size: 16px; color: red;font-weight: bold;" >{DangHoTro}</p>
        <a class="btn btn-danger" style="background-color: #fff;color: red;padding: 10px 50px" href="" >Gọi ngay: {SDTHoTro}</a>
    </div>
</div>

