<div class="col-lg-12" style="margin-top: 30px;" >
    <div class="col-lg-6 col-md-6" >
        <table class="table table-bordered" style="border: 0px;" >
            <tr style="border: 0px solid #fff;" >
                <td style="height: 180px;border: 0px solid #fff;" ></td>
            </tr>
            <tr>
                <td>Vị Trí Hiển Thị</td>
            </tr>
            <tr>
                <td>Thời Gian Lưu Tin</td>
            </tr>
            <tr>
                <td>Khuyến Mãi</td>
            </tr>
            <tr>
                <td>Số Trang Liên Kết Đăng Tin</td>
            </tr>
            <tr>
                <td>Ưu Tiên Tìm Kiếm</td>
            </tr>
            <tr>
                <td>Hiển thị thêm tại trang chi tiết các tin</td>
            </tr>
        </table>
    </div>
    <div class="col-lg-3 col-md-3" >
        <table class="table table-bordered text-center" >
            <tr>
                <td class="text-center" style="padding: 0px;position: relative;height: 180px;" >
                    <h3 class="text-center" style="text-transform: uppercase;background-color: #0f76bf;color: #fff;margin: 0px;height: 80px;position: absolute;width: 100%;z-index: 0;padding-top: 20px;font-size: 16px;" >Gói Basic</h3>
                    <div class="text-center" style="position: absolute;top: 40px;width: 100%;" >
                        <img src="<?php echo BASE_DIR ?>public/home/img/goibaysic.png" alt=""/>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Phần Tin Chính</td>
            </tr>
            <tr>
                <td>Khi sang nhượng thành công</td>
            </tr>
            <tr>
                <td>Không</td>
            </tr>
            <tr>
                <td>4 Trang</td>
            </tr>
            <tr>
                <td>Cao</td>
            </tr>
            <tr>
                <td>Không</td>
            </tr>
            <tr>
                <td>
                    <a href="<?php echo BASE_DIR ?>dangtin" class="btn btn-primary" >Đăng Ký</a>
                </td>
            </tr>
        </table>
    </div>
    <div class="col-lg-3 col-md-3" >
        <table class="table table-bordered text-center" >
            <tr>
                <td class="text-center" style="padding: 0px;position: relative;height: 180px;" >
                    <h3 class="text-center" style="text-transform: uppercase;background-color: red;color: #fff;margin: 0px;height: 80px;position: absolute;width: 100%;z-index: 0;padding-top: 20px;font-size: 16px;" >Gói Maximum</h3>
                    <div class="text-center" style="position: absolute;top: 40px;width: 100%;" >
                        <img src="<?php echo BASE_DIR ?>public/home/img/maximun.png" alt=""/>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Tin Góc Phải</td>
            </tr>
            <tr>
                <td>Khi sang nhượng thành công</td>
            </tr>
            <tr>
                <td>Tặng Gói Basic</td>
            </tr>
            <tr>
                <td>4 Trang</td>
            </tr>
            <tr>
                <td>Cao Nhất</td>
            </tr>
            <tr>
                <td>Có</td>
            </tr>
            <tr>
                <td>
                    <a href="<?php echo BASE_DIR ?>dangtin/" class="btn btn-danger" >Đăng Ký</a>
                </td>
            </tr>
        </table>
    </div>
</div>