<div class="clearfix" style="margin-bottom: 20px;" ></div>
<div class="col-lg-12 col-md-12 listSanPham " >
    <div class="row" id="NoiDung" >
        <div ng-repeat="item in _SanPhamTranChu" class="col-sm-4 col-xs-4"  >
            <div class="SanPhamHome" >
                <div >
                    <div class="SanPhamImg" >
                        <img src="{{item.UrlHinh}}" class="img img-sanpham img-responsive"  >
                    </div>
                    <span class="bnt-gia btn-sm pull-left"  >{{item.GiaVND}}</span>
                    <a href="{{item.Link}}" >
                        <h3 class="title"  >
                            {{item.TieuDe}}
                        </h3>
                    </a>
                    <a href="tel:{{item.DienThoai}}" style="font-weight: bold;" class="center-block"  >
                        <i class="fa fa-phone " style="border: 1px solid #18baa5;padding: 2px;" ></i>
                        {{item.DienThoai}}({{item.NguoiLienHe}})
                    </a>
                    <span class="lblKhuVuc"  >Khu Vực: {{item.KhuVuc}}</span>
                    <div class="clearfix" > </div>
                </div>
                <div class="clearfix" ></div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix" ></div>
