<?php 
$Model_QuanCao = new Model_QuanCao();

?>
<div class="container-fluid" >
    <div class="panel panel-success">
        <div class="panel-heading bg-green "  >
            <h3 class="panel-title"  >
                Thêm Quảng Cáo
            </h3>
        </div>
        <div class="panel-body" >
            <form action="<?php $Model_QuanCao->getLinkThemQuanCao() ?>" method="POST" >
                <div class="col-md-4 col-lg-4" >
                    <table class="table table-bordered" >
                        <tr>
                            <td >
                                Tên Quảng Cáo
                                <input name="TenQuanCao" value="" class="form-control" required="required" >
                            </td>
                        </tr>
                        <tr>
                            <td >
                                Vị Trí
                                <input name="ViTri" value="1" class="form-control" required="required" >
                            </td>
                        </tr>
                        <tr>
                            <td >
                                STT
                                <input name="Stt" value="0" class="form-control" required="required" >
                            </td>
                        </tr>
                        <tr>
                            <td >
                                Link Quản Cáo
                                <input name="LinkQuanCao" value="" required="required" class="form-control" >
                            </td>
                        </tr>
                        <tr>
                            <td >
                                <input style="display: none;"  id="HinhSanPham" class="form-control" value="<?php echo BASE_DIR ?>public/img/images/" name="UrlHinh" type="text" size="60" />
                                <label style="position: relative;border: 1px solid blue;" >
                                    <span style="position: absolute;" >
                                        Hình Quảng Cáo
                                    </span> 
                                    <input style="display: none;" type="button"  value="Browse Server" onclick="BrowseServer('Images:/quangcao/', 'HinhSanPham');" />
                                    <img id="HinhQuanCao" src="" style="width: 200px;height: 200px;" >
                                </label>
                            </td>
                        </tr>
                        <tr>
                            <td >
                                <input type="submit"  value="Thêm" name="ThemQuanCao" class="btn btn-success btn-block" style="font-weight: bold "  />
                            </td>
                        </tr>
                    </table>                
                </div>
            </form>


        </div>
    </div>



</div>


