<?php
$View_Layout = new mobie_layout();
$View_quancaoview = new View_quancaoview();
ob_start();
?>
<!DOCTYPE HTML>
<html lang="vi" >
    <head>
        <?php $View_Layout->layouthead(); ?>        
    </head>
    <body>
        <?php
        $View_Layout->layoutMenuCom($_Controller, $_Param);
        ?>
        <div style="margin-top: 15px;" >
            <?php
            $View_quancaoview->ListQuanCao4ViTri(1);
            ?>
        </div>
        <?php
        include $Conten;
        ?>
        <?php
        $KhuVuc = "ho-chi-minh-32";
        if ($_Controller == 'sangquan') {
            $KhuVuc = $_Param[1];
        }
        $View_Layout->layoutLeft($KhuVuc);
        $View_Layout->layoutLienHe();
        $View_Layout->LayoutCopyright();
        ?>
        <script src="<?php echo BASE_DIR ?>public/home/js/bootstrap.js"></script>
        <script src="<?php echo BASE_DIR ?>public/home/js/owl.carousel.min.js" type="text/javascript"></script>


        <script>
            $(document).ready(function () {
//                window.oncontextmenu = new Function("return false;");
            });
            $('#link').click(function () {
                $("html, body").animate({scrollTop: 0}, 600);
                return false;
            });
        </script>
        <div id="fb-root"></div>
        <script>(function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id))
                    return;
                js = d.createElement(s);
                js.id = id;
                js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.9&appId=1235248759897668";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>
    </body>
</html>
<?php
$str = ob_get_clean();
$Model_Option = new Model_Option();
$DSOption = $Model_Option->DSOption();
foreach ($DSOption as $option) {
    $_Option = new Model_Option($option);
    $str = str_replace("{{$_Option->MaOption}}", $_Option->GiaTri, $str);
}
echo $str;
?>