<?php
$Model_DanhMuc = new Model_DanhMuc();
$DMChon = $Model_DanhMuc->DanhMuc($data['DMChon']);
?>
<form action="" method="POST">
    <input type="hidden" name="MaDanhMuc" value="<?php echo $Model_DanhMuc->MaDanhMuc ?>"  >
    <div class="panel panel-default">
        <div class="panel-heading" style="padding-left: 5px;">
            <a href="danhmuc" style="border: 1px solid #aaa;padding: 5px;margin-right: 10px;color: #000;height: 100%;margin-left: 5px">
                <i class="fa fa-arrow-left"></i>
            </a>
            Sửa Danh Mục 
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-4 col-md-4 " >
                    <div class="form-group">
                        <label for="">Danh Mục Cha</label>
                        <select class="form-control" name="CapCha" >
                            <option value="0" >Thêm Danh Mục</option>
                            <?php
                            $DSDanhMuc = $data['DSDanhMucCha'];
                            foreach ($DSDanhMuc as $DanhMuc) {
                                ?>
                                <option  <?php echo $Model_DanhMuc->CapCha == $DanhMuc['MaDanhMuc'] ? 'selected="selected"' : '' ?>  value="<?php echo $DanhMuc['MaDanhMuc']; ?>" ><?php echo $DanhMuc['TenDanhMuc']; ?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="">Tên Danh mục</label>
                        <input autofocus="autofocus" name="TenDanhMuc" value="<?php echo $Model_DanhMuc->TenDanhMuc ?>" id="" type="text" class="form-control" >
                    </div>
                    <div class="form-group">
                        <label for="">Tên Không dấu</label>
                        <input autofocus="autofocus" value="<?php echo $Model_DanhMuc->TenKhongDau ?>" name="TenKhongDau" id="" type="text" class="form-control" >
                    </div>
                    <div class="form-group">
                        <label for="STT">STT</label>
                        <input name="STT" id="STT" value="<?php echo $Model_DanhMuc->STT ?>" type="text"  class="form-control" >
                    </div>
                    <div class="form-group">
                        <label>Pages
                        </label>
                        <select name="LoaiDanhMuc" class="form-control"    >
                            <option value="0" >Chọn Pages</option>
                            <?php
                            $Model_Pages = new Model_Pages();
                            $DSPages = $Model_Pages->DSPages();
                            foreach ($DSPages as $Pages) {
                                $_Pages = new Model_Pages($Pages);
                                ?>
                                <option value="<?php echo $_Pages->Pagesid ?>" ><?php echo $_Pages->TieuDe ?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>
                    <div class="form-group">
                        Hình Danh Mục
                        <div id="thumbnail">
                            <img src="<?php echo $Model_DanhMuc->UrlHinh ?>" style="width: 100px;height: 100px;" >
                        </div>
                        <input class="form-control" value="<?php echo $Model_DanhMuc->UrlHinh ?>" name="UrlHinh" id="UrlHinh" type="text" />
                        <input  type="button" value="Browse Server" class="ChonSV" onclick="BrowseServer('Images:/danhmuc/', 'UrlHinh')" />
                        <div style="clear: both"></div>

                    </div>
                </div>
                <div class="col-lg-8 col-md-8 " >
                    <div class="row">
                        <div class="col-lg-12 col-md-12">
                            <div class="form-group">
                                <label for="LoaiDanhMuc">Nội Dung</label>
                                <textarea name="NoiDung" id="NoiDungChinh" ><?php echo $Model_DanhMuc->NoiDung ?></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" name="SuaDanhMuc" class="btn btn-primary">Sửa</button>
            <button type="reset"  class="btn btn-default">Làm Lại</button>
        </div>
    </div>
</form>

