<?php
$slide = $data['DanhGia'];
$_MaDanhMuc = $slide['MaDanhMuc'];
$Model_DanhGia = new Model_TinTuc($slide);
ob_start();
?>
<div class="panel panel-success ">
    <div class="panel-heading bg-green">
        <h3 class="panel-title">Danh Sách DanhGia </h3>
    </div>
    <div class="panel-body">
        <form action="" method="POST" class="form" >
            <div class="col-lg-3 col-md-3">
                <div class="row">
                    <input name="IdTin" type="hidden" value="<?php echo $Model_DanhGia->IDTin  ?>" >  
                    <input type="hidden" name="description" value="<?php echo $Model_DanhGia->description ?>" >  
                    <input name="MaDanhMuc" type="hidden" value="<?php echo $_MaDanhMuc ?>" >  
                    <input type="hidden" name="TieuDeKhongDau" value="<?php echo $Model_DanhGia->TieuDeKhongDau  ?>" >  

                    <div class="clearfix" style="margin-bottom: 10px" ></div> 
                    <div class="form-group-sm">
                        <div class="col-lg-12 col-md-12">
                            <h3>Phát Biểu</h3>
                            <input name="TieuDe" value="<?php echo $Model_DanhGia->TieuDe  ?>" class="form-control">  
                        </div>
                    </div>
                    <div class="form-group-sm">
                        <div class="col-lg-12 col-md-12">
                            <h3>Tên Người Nhật Xét</h3>
                            <input name="title" value="<?php echo $Model_DanhGia->title  ?>" class="form-control">  
                        </div>
                    </div>
                    <div class="form-group-sm">
                        <div class="col-lg-12 col-md-12">
                            <h3>Chức Vụ Người Nhật Xét</h3>
                            <input name="keyword" value="<?php echo $Model_DanhGia->keyword ?>" class="form-control">  
                        </div>
                    </div>
                    <div class="form-group-sm">
                        <div class="col-lg-12 col-md-12">
                            <h3>Tóm Tat</h3>
                            <textarea name="TomTat" rows="5" style="width: 100%;"  ><?php echo $Model_DanhGia->TomTat  ?></textarea>
                        </div>
                    </div>
                    <div class="clearfix" style="margin-bottom: 10px" ></div> <div class="form-group-sm">
                        <div class="col-lg-6 col-md-6">
                            <h3>{Stt}</h3>
                            <input name="Stt" value="<?php echo $Model_DanhGia->Stt  ?>" class="form-control">  
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <h3>{AnHien}</h3>
                            <input type="checkbox" name="AnHien" <?php echo $Model_DanhGia->AnHien==1?'checked="checked"':''  ?>  value="<?php echo $Model_DanhGia->AnHien  ?>" >  
                        </div>
                    </div>
                    <input type="hidden" name="NgayDang" value="<?php echo date("Y-m-d"); ?>" class="form-control">  
                    <div class="clearfix" style="margin-bottom: 10px" ></div> <div class="form-group-sm">
                        <label class="col-lg-2 col-md-2">{UrlHinh}</label>
                        <div class="col-lg-12 col-md-12">
                            <div class="clearfix" ></div>
                            <input class="form-control" value="<?php echo $Model_DanhGia->UrlHinh  ?>" id="UrlHinh" name="UrlHinh" type="text" />
                            <input  type="button" value="Browse Server" class="ChonSV" onclick="BrowseServer('Images:/slide/', 'UrlHinh')" />
                            <div class="clearfix"></div>
                            <div id="thumbnail" ></div>
                        </div>
                    </div>
                    <input type="hidden" name="TinNoiBat" value="0" >  
                    <input type="hidden" name="SoLanXem" value="0" class="form-control">  
                    <input type="hidden" name="lang" value="vi" class="form-control">  
                    <div class="clearfix" style="margin-bottom: 10px" ></div>
                    <div style="text-align: center;padding-top: 10px;">
                        <input name="SuaDanhGia" value="Sửa" type="submit"  class="btn btn-primary" >
                        <input  value="Làm Lại" type="reset"  class="btn btn-default" >
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-9">
                <div  class="row" >
                    <div class="clearfix" style="margin-bottom: 10px" ></div> <div class="form-group-sm">
                        {NoiDung}
                        <div class="col-lg-12 col-md-12">
                            <textarea name="NoiDung" id="NoiDungChinh" ><?php echo $slide['NoiDung']; ?></textarea>
                        </div>
                    </div>
                </div>  
            </div>
        </form>
    </div>
</div>
<?php
$str = ob_get_clean();
$str = str_replace("{NoiDung}", "Nội Dung", $str);
$str = str_replace("{AnHien}", "Ẩn Hiện", $str);
$str = str_replace("{UrlHinh}", "Hình", $str);
$str = str_replace("{Stt}", "STT", $str);
echo $str;
?>
