<?php
$slide = $data['DoiTac'];
$Model_DoiTac = new Model_TinTuc($slide);
$MDoiTac = new Model_DoiTac();
$_MaDanhMuc = $MDoiTac->GetDanhMucDoiTac();
ob_start();
?>
<div class="panel panel-success ">
    <div class="panel-heading bg-green">
        <h3 class="panel-title">Danh Sách Đối Tác </h3>
    </div>
    <div class="panel-body">
        <form action="" method="POST" class="form" >
            <div class="col-lg-6 col-md-6">
                <div class="row">
                    <input name="IdTin" value="<?php echo $Model_DoiTac->IDTin ?>" type="hidden" >  
                    <input type="hidden" name="description" value="<?php echo $Model_DoiTac->description ?>" >  
                    <input name="MaDanhMuc" type="hidden" value="<?php echo $_MaDanhMuc ?>" >  
                    <input type="hidden" name="TieuDeKhongDau" value="<?php echo $Model_DoiTac->TieuDeKhongDau ?>" >  
                    <input name="title"  value="<?php echo $Model_DoiTac->title ?>" type="hidden" >  
                    <input name="keyword"  value="<?php echo $Model_DoiTac->keyword ?>" type="hidden" >  
                    <input name="TomTat"  value="<?php echo $Model_DoiTac->TomTat ?>" type="hidden" >  
                    <div class="clearfix" style="margin-bottom: 10px" ></div> 
                    <div class="form-group-sm">
                        <div class="col-lg-12 col-md-12">
                            <h3 style="font-size: 20px;" >Tên Đối Tác</h3>
                            <input name="TieuDe"  value="<?php echo $Model_DoiTac->TieuDe ?>" class="form-control">  
                        </div>
                    </div>
                    <div class="clearfix" style="margin-bottom: 10px" ></div> 
                    <div class="form-group-sm">
                        <div class="col-lg-12 col-md-12">
                            <h3>{Stt}</h3>
                            <p style="color: red" >Thứ Tự xuất hiện của công ty thứ tự tăng dần</p>
                            <input name="Stt" value="<?php echo $Model_DoiTac->Stt ?>" class="form-control">  
                        </div>
                        <div class="col-lg-12 col-md-12">
                            <h3>{AnHien}</h3>
                            <p style="color: red" >Ẩn hiện công ty đối tác</p>
                            <input type="checkbox" name="AnHien" <?php echo $Model_DoiTac->AnHien == 1 ? 'checked="checked"' : '' ?>  value="1" >  
                        </div>
                    </div>
                    <input type="hidden" name="NgayDang" value="<?php echo date("Y-m-d"); ?>" class="form-control">  
                    <div class="clearfix" style="margin-bottom: 10px" ></div>

                    <input type="hidden" name="TinNoiBat" value="0" >  
                    <input type="hidden" name="SoLanXem" value="0" class="form-control">  
                    <input type="hidden" name="lang" value="vi" class="form-control">  
                    <div class="clearfix" style="margin-bottom: 10px" ></div>
                    <div style="text-align: center;padding-top: 10px;">
                        <input name="SuaDoiTac" value="Sửa" type="submit"  class="btn btn-primary" >
                        <input  value="Làm Lại" type="reset"  class="btn btn-default" >
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="form-group-sm">
                    <h3>Link</h3>
                    <p style='color: red' >Link Trang đến website của đối tác</p>
                    <div class="col-lg-12 col-md-12">
                        <input name="NoiDung" value="<?php echo $slide['NoiDung']; ?>" class="form-control" >
                    </div>
                </div>
                <div class="form-group-sm">
                    <h3 >{UrlHinh}</h3>
                    <div class="col-lg-12 col-md-12">
                        <div class="clearfix" ></div>
                        <input  style="display: none" class="form-control" value="<?php echo $Model_DoiTac->UrlHinh ?>" id="UrlHinh" name="UrlHinh" type="text" />
                        <label style="border: 1px solid #000;background-color: rgba(0, 0, 0, 0.34);color: #fff;text-align: center;position: relative;height: 105px;display: block;z-index: 2" >
                            Chọn Hình
                            <input  style="display: none;" type="button" value="Browse Server" class="ChonSV" onclick="BrowseServer('Images:/doitac/', 'UrlHinh')" />
                            <div class="HinhChon" style="position: absolute;top: 0px;z-index: 1" >
                                <img src="<?php echo $Model_DoiTac->UrlHinh ?>" style="height: 100px;opacity: 0.4" >
                            </div>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-9">
                <div  class="row" >
                    <div class="clearfix" style="margin-bottom: 10px" ></div> 
                </div>  
            </div>
        </form>
    </div>
</div>
<?php
$str = ob_get_clean();
$str = str_replace("{NoiDung}", "Nội Dung", $str);
$str = str_replace("{AnHien}", "Ẩn Hiện", $str);
$str = str_replace("{UrlHinh}", "Hình", $str);
$str = str_replace("{Stt}", "STT", $str);
echo $str;
?>
