<?php
$data['DSTinTuc'] = $data['DSTinHot'];
?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Bài Viết Quan Trọng</h3>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-hover" id="datatable">
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Danh Mục</th>
                    <th>Tiêu Đề</th>
                    <th>Hình</th>
                    <th>Hot</th>
                    <th>Ẩn Hiển</th>
                    <th>Thao Tác</th>
                </tr>
            </thead>
            <tbody>
                <?php
                if ($data['DSTinTuc']) {
                    $Dem = 1;
                    foreach ($data['DSTinTuc'] as $TinTuc) {
                        $_TinTuc = new Model_TinTuc($TinTuc);
                        ?>   
                        <tr>
                            <td><?php echo $Dem ?></td>
                            <td><?php echo $_TinTuc->TenDanhMuc; ?></td>
                            <td><?php echo $TinTuc['TieuDe'] ?></td>
                            <td><img style="width: 30px;height: 30px;" src="<?php echo BASE_DIR ?>public/img/images/<?php echo $TinTuc['UrlHinh'] ?>" /></td>

                            <td>
                                <input id="<?php echo $TinTuc['IdTin'] ?>" onchange="AnHienTinNoiBat('<?php echo $TinTuc['IdTin'] ?>')"  <?php echo $TinTuc['TinNoiBat'] == 1 ? "checked='checked'" : ""; ?>  type="checkbox" >                        
                            </td>
                            <td>
                                <input id="<?php echo $TinTuc['IdTin'] ?>" onchange="AnHienTin('<?php echo $TinTuc['IdTin'] ?>')"  <?php echo $TinTuc['AnHien'] == 1 ? "checked='checked'" : ""; ?>  type="checkbox" >
                            </td>
                            <td style="width: 100px;">
                                <div class="btn-group">
                                    <a class="btn btn-success" href="<?php echo BASE_DIR ?>quantri/tintucsua/<?php echo $TinTuc['IdTin']; ?>"><i class="fa fa-check"></i></a>
                                    <a class="btn btn-danger xoa" href="<?php echo BASE_DIR ?>quantri/xoatintuc/<?php echo $TinTuc['IdTin']; ?>"><i class="fa fa-close"></i></a>
                                </div>
                            </td>
                        </tr>
                        <?php
                        $Dem++;
                    }
                }
                ?>
            </tbody>
            <tfoot>
                <tr>
                    <th>STT</th>
                    <th>Danh Mục</th>
                    <th>Tiêu Đề</th>
                    <th>Hình</th>
                    <th>Hot</th>
                    <th>Ẩn Hiển</th>
                    <th>Thao Tác</th>
                </tr>
            </tfoot>
        </table>
    </div>

</div>


<script>
    function AnHienTin(IdTin) {

        var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function () {
            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {


            }
        };
        xmlhttp.open("GET", "<?php echo BASE_URL ?>quantri/tintucanhien/" + IdTin, true);
        xmlhttp.send();
    }
    function AnHienTinNoiBat(IdTin) {

        var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function () {
            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                document.getElementById('ThongBao').innerHTML = "ok";
            }
        };
        xmlhttp.open("GET", "<?php echo BASE_URL ?>quantri/tintucanhiennoibat/" + IdTin, true);
        xmlhttp.send();
    }

</script>
