<!DOCTYPE html>
<html>
   <head>
      <meta charset="UTF-8">
      <title>AdminLTE 2 | Log in</title>
      <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
      <link href="<?php echo BASE_DIR ?>public/templateadmin/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
      <link href="<?php echo BASE_DIR ?>public/templateadmin/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
      <link href="<?php echo BASE_DIR ?>public/templateadmin/plugins/iCheck/square/blue.css" rel="stylesheet" type="text/css" />
   </head>
   <body class="login-page">
      <div class="login-box">
         <div class="login-box">
            <div class="login-logo">
               <h3>Đăng Nhập</h3>
            </div><!-- /.login-logo -->
            <div class="login-box-body">
               <p class="login-box-msg">Đăng nhập để bắt đâu phiền làm việc</p>
               <form method="post" action="<?php echo BASE_DIR ?>quantri/login">
                  <div class="form-group has-feedback">
                      <input type="text" autofocus="autofocus" class="form-control" name="user" placeholder="Email">
                     <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                  </div>
                  <div class="form-group has-feedback">
                     <input type="password" class="form-control" name="pass" placeholder="Password">
                     <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                  </div>
                  <div class="form-group has-feedback">
                     <input type="password" class="form-control" name="gfa" placeholder="2FA code">
                     <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                  </div>
                  <div class="row">
                     <div class="col-xs-4">
                        <button type="submit" name="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                     </div><!-- /.col -->
                  </div>
               </form>
               <a href="<?php echo BASE_DIR ?>quantri/quenmatkhau/">I forgot my password</a><br>
            </div><!-- /.login-box-body -->
         </div><!-- /.login-box -->
      </div><!-- /.login-box -->
      <script src="<?php echo BASE_DIR ?>public/templateadmin/plugins/jQuery/jQuery-2.1.4.min.js" type="text/javascript"></script>
      <script src="<?php echo BASE_DIR ?>public/templateadmin/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
      <script src="<?php echo BASE_DIR ?>public/templateadmin/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
      <script>
         $(function () {
	  $('input').iCheck({
	     checkboxClass: 'icheckbox_square-blue',
	     radioClass: 'iradio_square-blue',
	     increaseArea: '20%' 
	  });
         });
      </script>
   </body>
</html>




