<form id="form1" name="form1" method="post" action="<?php echo BASE_DIR ?>quantri/quenmatkhau">

   <table width="400" border="0" align="center" cellpadding="5" style="width:400px; margin:auto">
      <caption>
         nhập email của ban đã đăng ký với chún tôi để nhận lại mật khẩu!
      </caption>
      <tr>
         <td width="95">Email</td>
         <td width="279"><input class="form-control" value="" type="text" name="Email" id="user" /></td>
      </tr>
      <tr>
         <td>&nbsp;</td>
         <td><input type="submit" name="submit" id="submit" value="Gửi" /></td>
      </tr>

   </table>
</form>