
<form action="<?php echo BASE_DIR ?>quantri/themmenu" method="POST">
   <table style="width: 100%;">
      <tr>
         <td>Tiêu Đề</td>
         <td><input value="" name="TieuDe" type="text" ></td>
      </tr>
      <tr>
         <td>Link</td>
         <td><input value="" name="Link" type="text" ></td>
      </tr>
      <tr>
         <td>Thứ Tự</td>
         <td><input value="" name="ThuTu" type="text" ></td>
      </tr>
      <tr>
         <td>Cấp Cha</td>
         <td>

	  <select name="CapCha">
	     <option value="0">Cấp Cha</option>
	     <?php
	     foreach($data['DSMenuCha'] as $DSMenu) {
	        ?>
	     <option  value="<?php echo $DSMenu['MaMenu'] ?>"><?php echo $DSMenu['TieuDe'] ?></option>
	        <?php
	     }
	     ?>
	  </select>
         </td>
      </tr>
      <tr>
         <td>Ẩn Hiện</td>
         <td><input value="1" name="AnHien" type="checkbox" ></td>
      </tr>
   </table>
   <button name="ThemMenu" type="submit">Them</button>
</form>