<?php
$TinTuc = $data['TinTuc'];
$TinTuc = new Model_TinTuc($TinTuc);
$DSLoaiTin = $data['DSLoaiTin'];
$Model_Pages = new Model_Pages();
$DSPages = $Model_Pages->DSPages();
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <a  href="<?php echo BASE_DIR ?>quantri/tintuc">
            <i class="btn btn-primary fa fa-arrow-left fa-border" ></i>
        </a>
        Sửa Bài Viết
    </div>
    <div class="panel-body">
        <form action="" method="post" enctype="multipart/form-data" >
            <div class="col-lg-9 col-md-9 " style="padding: 0px;margin: 0px;">
                <table class="table table-bordered" >
                    <tr>
                        <td colspan="2" >
                            <h4>
                                Tiêu Đề Tin(không quá 200 ký tự).
                            </h4>
                            <input name="TieuDe" class="form-control" value="<?php echo $TinTuc->TieuDe ?>" name="TieuDe" >
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <h4>Tóm Tắt</h4>
                            <textarea id="NoiDungTomTat" class="ckeditor" name="TomTat"><?php echo $TinTuc->TomTat ?></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <h4>Nội Dung</h4>
                            <textarea name="NoiDung" id="NoiDungChinh" ><?php echo $TinTuc->NoiDung ?></textarea>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-lg-3 col-md-3 " >
                <table class="table table-bordered"> 
                    <tr>
                        <td colspan="2" >
                            <h4>Danh Mục Bài Viết</h4>
                            <select name="MaDanhMuc" class="form-control" >
                                <?php
                                if ($DSPages)
                                    foreach ($DSPages as $Page) {
                                        $_Pages = new Model_Pages($Page);
                                        ?>
                                        <option <?php echo $TinTuc->MaDanhMuc == $_Pages->Pagesid ? 'selected="selected"' : '' ?>  value="<?php echo $_Pages->Pagesid ?>" ><?php echo $_Pages->TieuDe ?></option>
                                        <?php
                                    }
                                ?>
                            </select>  
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            keyword
                            <textarea class="form-control"  name="keyword" cols="10" rows="4"  ><?php echo $TinTuc->keyword ?></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            description
                            <textarea class="form-control"  name="description" cols="10" rows="4"  ><?php echo $TinTuc->description ?></textarea>

                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            Title
                            <textarea class="form-control"  name="title" cols="10" rows="4"  ><?php echo $TinTuc->title ?></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td>Ẩn Hiện</td>
                        <td>
                            <div class="slideThree">	
                                <input type="checkbox" <?php echo $TinTuc->AnHien ? 'checked="checked"' : "" ?> value="1" id="slideThree" name="AnHien" />
                                <label for="slideThree"></label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>Nổi Bật</td>
                        <td>
                            <div class="slideThree">	
                                <input type="checkbox" <?php echo $TinTuc->TinNoiBat ? 'checked="checked"' : "" ?> value="1" id="slideFor" name="TinNoiBat" />
                                <label for="slideFor"></label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>Thứ Tự</td>
                        <td>
                            <input   name="Stt" value="<?php echo $TinTuc->Stt ?>" type="text" >
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            Hình Ảnh
                            <input  style="display: none" type=text name="UrlHinh" id="UrlHinh" class="form-control"  value="<?php echo $TinTuc->UrlHinh ?>" />

                            <label style="border: 1px solid #000;background-color: rgba(0, 0, 0, 0.34);color: #fff;text-align: center;position: relative;height: 105px;display: block;z-index: 2" >
                                Chọn Hình
                                <input style="display: none" onclick="BrowseServer('Images:/tintuc/', 'UrlHinh')"  type="button" name="btnChonFile" id="btnChonFile" value="Chọn File" />
                                <div class="HinhChon" style="position: absolute;top: 0px;z-index: 1" >
                                    <img src="<?php echo $TinTuc->UrlHinh ?>" style="height: 100px;max-width: 200px"  >
                                </div>
                            </label>
                            <div style="clear: both"></div>
                            
                        </td>
                    </tr>
                    <tr>
                        <th colspan="2">
                            <input class=" btn btn-success btn-block"  name="sua"  type="submit" value="Sửa" >
                            <input name="IdTin"  type="hidden" value="<?php echo $TinTuc->IDTin ?>" >
                        </th>
                    </tr>

                </table>
            </div>
        </form>
    </div>
</div>


<div class="clearfix"></div>
<div class="modal fade" id="modal-id">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Tạo Danh Sách Hình</h4>
            </div>
            <div class="modal-body">
                <label>Đường Dẫn Hình</label>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Tạo</button>
            </div>
        </div>
    </div>
</div>