<?php
$_SanPham = new Model_SanPham($data['SanPham']);
?>
<div class="clearfix" ></div>
<div class="col-lg-6 col-md-6">
    <div class=" owl-carouselChiTiet" >
        <div class="item" >
            <img style="height: 350px;" title="<?php echo $_SanPham->TenSP ?>" alt="<?php echo $_SanPham->TenSP ?>" src="<?php echo $_SanPham->UrlHinh; ?>">
        </div>
        <?php
        $dem = 2;
        if ($_SanPham->ListHinh)
            foreach ($_SanPham->ListHinh as $TenHinh) {
                ?>
                <div class="item" >
                    <img style="height: 350px;" title="<?php echo $_SanPham->TenSP ?>" alt="<?php echo $_SanPham->TenSP ?>" src="<?php echo $TenHinh ?>">
                </div>
                <?php
            }
        ?>
        <div class="item" >
            <img style="height: 350px;" title="<?php echo $_SanPham->TenSP ?>" alt="<?php echo $_SanPham->TenSP ?>" src="<?php echo $_SanPham->UrlHinh; ?>">
        </div>
    </div>
</div>
<div class="col-lg-6 col-md-6">
    <div style="background-color: #dbeae7" class="text-center ThongTinChungTin" >
        <table class="table table-bordered" >
            <tr>
                <th>Mã Tin</th>
                <th><?php echo $_SanPham->MaSP ?></th>
            </tr>
            <tr>
                <th>Danh Mục</th>
                <th><?php echo $_SanPham->TenDanhMuc ?></th>
            </tr>
            <tr>
                <th>Khu Vực</th>
                <th><?php echo $_SanPham->TenHuyen ?>-<?php echo $_SanPham->TenTinh ?></th>
            </tr>
            <tr>
                <th>Vị Trí</th>
                <th><?php echo $_SanPham->TenViTri ?></th>
            </tr>
            <tr>
                <th>Giá</th>
                <th>
                    <h3 style="display: table;border: 1px solid red;color: red;padding: 10px;border-radius: 3px;font-weight: bold; " >
                        <?php echo $_SanPham->GiaVND ?>
                    </h3>
                </th>
            </tr>
            <tr>
                <th>Người Sang</th>
                <th>
                    <?php echo $_SanPham->NguoiLienHe ?>
                </th>
            </tr>
            <tr>
                <th>Số Điện Thoại</th>
                <th style="color: green" >
                    <?php echo $_SanPham->DienThoai ?>
                </th>
            </tr>
            <tr>
                <th colspan="2" >Địa Chỉ : 
                    <?php
                    echo $_SanPham->DiaChi;
                    ?>
                </th>
            </tr>
        </table>
        <div class="clearfix" ></div>
    </div>
</div>
<div class="clearfix" ></div>
<div class="row" >
    <div class="col-lg-12 col-md-12" >
        <h1 style="color: #055699;" >
            <?php echo $_SanPham->TenSP; ?>
        </h1>
        <div class="clearfix" ></div>
        <div >
            <h3 style="display: table;border: 1px solid red;color: red;padding: 10px;border-radius: 3px;font-weight: bold; " >
                <?php echo $_SanPham->GiaVND ?>
            </h3>
        </div>
        <div class="text-justify table-responsive NoiDungSanPham">
            <?php echo $_SanPham->NoiDung ?>
        </div>
    </div>
    <div class="clearfix" ></div>
    <div class="col-lg-12 col-md-12" >
        <h4 class="tieudeTin" >Thông Tin Chủ Sang nhượng</h4>
        <div class="col-lg-6 col-md-6" >
            <h3 class="btn btn-success btn-block btn-nguoilienhe" >
                Vui Lòng Liên Hệ: <?php echo $_SanPham->NguoiLienHe; ?> </h3>
        </div>
        <div class="col-lg-6 col-md-6" >
            <h3 class="btn btn-success btn-block btn-nguoilienhe" >Điện Thoại: <?php echo $_SanPham->DienThoai; ?> </h3>
        </div>
    </div>
    <div class="clearfix" ></div>
    <div class="col-lg-12 col-md-12 " style="margin-top: 20px;"  >
        <div class="alert alert-info" style="margin-bottom: 30px" >
            {Lang_TBChiTiet}
        </div>
    </div>
</div>
<div id="myModal" class="modal">
    <span class="close cursor" onclick="closeModal()">&times;</span>
    <div class="modal-content">
        <div id="carousel-id999" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-id999" data-slide-to="0" class=""></li>
                <li data-target="#carousel-id999" data-slide-to="1" class=""></li>
                <li data-target="#carousel-id999" data-slide-to="2" class="active"></li>
            </ol>
            <div class="carousel-inner">
                <?php
                $dem = 1;
                if ($_SanPham->ListHinh)
                    foreach ($_SanPham->ListHinh as $TenHinh) {
                        ?>
                        <div class="item <?php echo $dem == 1 ? 'active' : '' ?>">
                            <img src="<?php echo $TenHinh ?>" style="margin: auto;width:auto;max-height: 500px;" onclick="currentSlide(<?php echo $dem++; ?>)" alt="Nature and sunrise">
                        </div>
                        <?php
                        $dem++;
                    }
                ?>
            </div>
            <a class="left carousel-control" href="#carousel-id999" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
            <a class="right carousel-control" href="#carousel-id999" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </div>
</div>
<link href="<?php echo BASE_DIR ?>public/home/css/owl.carousel.min.css" rel="stylesheet" type="text/css"/>
<script src="<?php echo BASE_DIR ?>public/home/js/owl.carousel.min.js" type="text/javascript"></script>
<script type="text/javascript" >
                                function openModal() {
                                    document.getElementById('myModal').style.display = "block";
                                }

                                function closeModal() {
                                    document.getElementById('myModal').style.display = "none";
                                }
                                $(document).ready(function() {
                                    $('.owl-carousel').owlCarousel({
                                        loop: true,
                                        margin: 10,
                                        stagePadding: 0,
                                        autoplay: true,
                                        autoplayTimeout: 1500,
                                        responsive: {
                                            0: {
                                                items: 1
                                            },
                                            600: {
                                                items: 4
                                            },
                                            1000: {
                                                items: 4
                                            }
                                        }
                                    });
                                    $('.owl-carouselChiTiet').owlCarousel({
                                        loop: true,
                                        margin: 10,
                                        stagePadding: 0,
                                        autoplay: true,
                                        autoplayTimeout: 1500,
                                        responsive: {
                                            0: {
                                                items: 1
                                            },
                                            600: {
                                                items: 1
                                            },
                                            1000: {
                                                items: 1
                                            }
                                        }
                                    });
                                });
</script>

