<ol class="breadcrumb">
    <li><a href="<?php echo BASE_DIR ?>quantri/">Quản Trị Chung</a></li>
    <li class="active">Tỉnh Thành</li>
</ol>
<?php
$_Param[0] = isset($_Param[0]) ? $_Param[0] : 0;
$_Param[0] = intval($_Param[0]);

$Model_TinhThanhThanh = new Model_TinhThanh();
$DSTinh = $Model_TinhThanhThanh->DSHuyenTheoTinh($_Param[0]);
?>
<style>
    input:checked{
        background-color: #aaa;
    }
</style>
<div class="container-fluid">
    <div class="box box-success">
        <div class="box-body">
            <div class="" >
                <form action="<?php echo BASE_DIR ?>" method="POST" >
                    <table class="table table-hover table-compare" id="datatable" >
                        <thead>
                            <tr>
                                <th>Action</th>
                                <th>Mã Tinh</th>
                                <th>Tên Tinh</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($DSTinh) {
                                foreach ($DSTinh as $k => $Tinh) {
                                    $_Tinh = new Model_TinhThanh($Tinh);
                                    ob_start();
                                    ?>
                                    <tr>
                                        <td style="width: 200px;" >
                                            <input name="idPa[{idTinh}]" value="{idTinh}" class="checkbox1"  type="checkbox" style="margin-right: 10px" >
                                            <a href="<?php echo $_Tinh->LinkSuaTinhThanh ?>" >
                                                <i class="fa fa-edit"></i>
                                                Sửa</a>
                                            |<a class="xoa" href="<?php echo $_Tinh->LinkXoaTinhThanh ?>" >
                                                <i class="fa fa-dot-circle-o"></i>
                                                xóa
                                            </a>
                                            |<a class="" href="<?php echo $_Tinh->LinkXemTinhThanh ?>" >
                                                <i class="fa fa-eye"></i>
                                                Xem
                                            </a>
                                        </td>
                                        <td>{MaTinh}</td>
                                        <td>{TenTinh}</td>
                                    </tr>
                                    <?php
                                    $str = ob_get_clean();
                                    $str = str_replace("{TenTinh}", $_Tinh->TenDiaChi, $str);
                                    $str = str_replace("{MaTinh}", $_Tinh->MaDiaChi, $str);
                                    echo $str;
                                }
                                unset($DSTinh[$k]);
                            }
                            ?>                
                        </tbody>
                        <tfoot>

                        </tfoot>
                        <tr>
                            <th>Action</th>
                            <th>Mã Tinh</th>
                            <th>Tên Tinh</th>
                        </tr> 
                    </table>    
                </form>    
            </div>

        </div>


    </div>

</div>
