<section class="container-fluid">
    <div class="slideInLeft" ></div>
    <div class="row" >
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Tim Nổi Bật</h3>
            </div>
            <div class="box-body">
                Start creating your amazing application!
            </div>
            <div class="box-footer">
                Footer
            </div>
        </div>
    </div>


</section>