<table>                        <tr>
                <td>
                    MaSP
                </td>
                <td>
                    <input name="MaSP" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->MaSP ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    ListHinh
                </td>
                <td>
                    <input name="ListHinh" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->ListHinh ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    IDKhachHang
                </td>
                <td>
                    <input name="IDKhachHang" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->IDKhachHang ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    title
                </td>
                <td>
                    <input name="title" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->title ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    keyword
                </td>
                <td>
                    <input name="keyword" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->keyword ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    description
                </td>
                <td>
                    <input name="description" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->description ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    MaDanhMuc
                </td>
                <td>
                    <input name="MaDanhMuc" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->MaDanhMuc ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    TenDanhMuc
                </td>
                <td>
                    <input name="TenDanhMuc" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->TenDanhMuc ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    TenSP
                </td>
                <td>
                    <input name="TenSP" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->TenSP ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    TenSPKhongDau
                </td>
                <td>
                    <input name="TenSPKhongDau" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->TenSPKhongDau ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    TomTat
                </td>
                <td>
                    <input name="TomTat" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->TomTat ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    NoiDung
                </td>
                <td>
                    <input name="NoiDung" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->NoiDung ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    NoiDungSua
                </td>
                <td>
                    <input name="NoiDungSua" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->NoiDungSua ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    AnHien
                </td>
                <td>
                    <input name="AnHien" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->AnHien ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    NgayDang
                </td>
                <td>
                    <input name="NgayDang" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->NgayDang ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    UrlHinh
                </td>
                <td>
                    <input name="UrlHinh" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->UrlHinh ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    TinNoiBat
                </td>
                <td>
                    <input name="TinNoiBat" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->TinNoiBat ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    SoLanXem
                </td>
                <td>
                    <input name="SoLanXem" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->SoLanXem ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    Stt
                </td>
                <td>
                    <input name="Stt" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->Stt ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    LinkChiTiet
                </td>
                <td>
                    <input name="LinkChiTiet" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->LinkChiTiet ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    LinkFullChiTiet
                </td>
                <td>
                    <input name="LinkFullChiTiet" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->LinkFullChiTiet ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    LinkGioHang
                </td>
                <td>
                    <input name="LinkGioHang" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->LinkGioHang ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    TangSLGioHang
                </td>
                <td>
                    <input name="TangSLGioHang" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->TangSLGioHang ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    GiamSLGioHang
                </td>
                <td>
                    <input name="GiamSLGioHang" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->GiamSLGioHang ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    GoiDangTin
                </td>
                <td>
                    <input name="GoiDangTin" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->GoiDangTin ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    TenGoiDangTin
                </td>
                <td>
                    <input name="TenGoiDangTin" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->TenGoiDangTin ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    XoaGioHang
                </td>
                <td>
                    <input name="XoaGioHang" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->XoaGioHang ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    Gia
                </td>
                <td>
                    <input name="Gia" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->Gia ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    SoLuong
                </td>
                <td>
                    <input name="SoLuong" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->SoLuong ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    Tinh
                </td>
                <td>
                    <input name="Tinh" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->Tinh ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    TenTinh
                </td>
                <td>
                    <input name="TenTinh" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->TenTinh ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    NguoiLienHe
                </td>
                <td>
                    <input name="NguoiLienHe" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->NguoiLienHe ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    DienThoai
                </td>
                <td>
                    <input name="DienThoai" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->DienThoai ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    ChieuNgang
                </td>
                <td>
                    <input name="ChieuNgang" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->ChieuNgang ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    ChieuRong
                </td>
                <td>
                    <input name="ChieuRong" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->ChieuRong ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    HienGia
                </td>
                <td>
                    <input name="HienGia" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->HienGia ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    ViTri
                </td>
                <td>
                    <input name="ViTri" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->ViTri ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    TenViTri
                </td>
                <td>
                    <input name="TenViTri" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->TenViTri ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    PhongCach
                </td>
                <td>
                    <input name="PhongCach" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->PhongCach ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    TenPhongCach
                </td>
                <td>
                    <input name="TenPhongCach" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->TenPhongCach ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    SoPhong
                </td>
                <td>
                    <input name="SoPhong" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->SoPhong ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    Toilet
                </td>
                <td>
                    <input name="Toilet" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->Toilet ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    TenHuyen
                </td>
                <td>
                    <input name="TenHuyen" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->TenHuyen ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    DoQuanTrong
                </td>
                <td>
                    <input name="DoQuanTrong" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->DoQuanTrong ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    Huyen
                </td>
                <td>
                    <input name="Huyen" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->Huyen ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    GiaVND
                </td>
                <td>
                    <input name="GiaVND" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->GiaVND ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    DonVi
                </td>
                <td>
                    <input name="DonVi" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->DonVi ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    NoiDungHH
                </td>
                <td>
                    <input name="NoiDungHH" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->NoiDungHH ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    CapCha
                </td>
                <td>
                    <input name="CapCha" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->CapCha ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    Title
                </td>
                <td>
                    <input name="Title" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->Title ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    Des
                </td>
                <td>
                    <input name="Des" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->Des ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    keywords
                </td>
                <td>
                    <input name="keywords" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->keywords ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    STT
                </td>
                <td>
                    <input name="STT" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->STT ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    LoaiDanhMuc
                </td>
                <td>
                    <input name="LoaiDanhMuc" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->LoaiDanhMuc ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    TenKhongDau
                </td>
                <td>
                    <input name="TenKhongDau" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->TenKhongDau ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    ThuocTinh
                </td>
                <td>
                    <input name="ThuocTinh" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->ThuocTinh ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    CapCon
                </td>
                <td>
                    <input name="CapCon" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->CapCon ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    LinkDanhMuc
                </td>
                <td>
                    <input name="LinkDanhMuc" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->LinkDanhMuc ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    LinkSuaDanhMuc
                </td>
                <td>
                    <input name="LinkSuaDanhMuc" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->LinkSuaDanhMuc ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    LinkThemDanhMuc
                </td>
                <td>
                    <input name="LinkThemDanhMuc" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->LinkThemDanhMuc ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    LinkXoaDanhMuc
                </td>
                <td>
                    <input name="LinkXoaDanhMuc" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->LinkXoaDanhMuc ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    LinkListDanhMuc
                </td>
                <td>
                    <input name="LinkListDanhMuc" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->LinkListDanhMuc ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    ViewDanhMuc
                </td>
                <td>
                    <input name="ViewDanhMuc" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->ViewDanhMuc ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    DanhMucLienQuan1
                </td>
                <td>
                    <input name="DanhMucLienQuan1" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->DanhMucLienQuan1 ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    DanhMucLienQuan2
                </td>
                <td>
                    <input name="DanhMucLienQuan2" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->DanhMucLienQuan2 ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    MaDiaChi
                </td>
                <td>
                    <input name="MaDiaChi" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->MaDiaChi ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    TenDiaChi
                </td>
                <td>
                    <input name="TenDiaChi" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->TenDiaChi ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    TenDiaChiCha
                </td>
                <td>
                    <input name="TenDiaChiCha" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->TenDiaChiCha ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    MaDiaChiCha
                </td>
                <td>
                    <input name="MaDiaChiCha" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->MaDiaChiCha ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    GhiChu
                </td>
                <td>
                    <input name="GhiChu" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->GhiChu ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    LinkXemTinhThanh
                </td>
                <td>
                    <input name="LinkXemTinhThanh" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->LinkXemTinhThanh ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    LinkXoaTinhThanh
                </td>
                <td>
                    <input name="LinkXoaTinhThanh" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->LinkXoaTinhThanh ?>"  >
                </td>
            </tr>                        <tr>
                <td>
                    LinkSuaTinhThanh
                </td>
                <td>
                    <input name="LinkSuaTinhThanh" class="btn btn-success" type="text" value="<?php echo $_Model_SanPham->LinkSuaTinhThanh ?>"  >
                </td>
            </tr></table>