<?php
$View_Layout = new View_layout();
$View_quancaoview = new View_quancaoview();
ob_start();
?>
<!DOCTYPE HTML>
<html lang="vi" >
    <head>
        <?php $View_Layout->layouthead(); ?>        
    </head>
    <body>
        <?php
//        $View_Layout->viewTopMenu();

        $View_Layout->layoutMenuCom($_Controller,$_Param);
        ?>
        <div class="container" >
            <div class="row" >
                <div class="panel panel-default" style="border-color: #fff; " >
                    <div class="panel-body" style="padding-top: 0px; " >
                        <div class="row" >
                            <div class="col-lg-9 col-md-9" >
                                <div class="row"  >
                                    <div style="margin-top: 15px;" >
                                        <?php
                                        $View_quancaoview->ListQuanCao4ViTri(1);
                                        ?>
                                    </div>
                                    <div class="clearfix" ></div>
                                    <?php
                                    include $Conten;
                                    ?>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3" >
                                <?php
                                $KhuVuc = "ho-chi-minh-32";
                                if ($_Controller == 'sangquan') {
                                    $KhuVuc = $_Param[1];
                                }
                                $View_Layout->layoutLeft($KhuVuc);
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php
        $View_Layout->layoutLienHe();
        $View_Layout->LayoutCopyright();
//        $View_Layout->chontienvung();
        ?>

        <script src="<?php echo BASE_DIR ?>public/home/js/bootstrap.js"></script>
        <script src="<?php echo BASE_DIR ?>public/home/js/owl.carousel.min.js" type="text/javascript"></script>
        <script>
            $(document).ready(function () {
//                window.oncontextmenu = new Function("return false;");
            });
            $('#link').click(function () {
                $("html, body").animate({scrollTop: 0}, 600);
                return false;
            });
        </script>
        <div id="fb-root"></div>
        <script>(function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id))
                    return;
                js = d.createElement(s);
                js.id = id;
                js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.9&appId=1235248759897668";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>

    </body>
</html>
<?php
include 'dinhnghia.php';
?>