<?php
$NVHienTaiXem = new Model_QuanTri($data['NhanVien']);
$Model_QuangTri = new Model_QuanTri();
$NVHienTai = $NVHienTaiXem->NhanVienHienTai();
?>
<div class="panel panel-default" >
    <div class="panel-heading" >
        <h3 class="panel-title" >Thông Tin Nhân Viên</h3>
    </div>
    <div class="panel-body" >
        <div class="col-lg-8 col-md-8 " >
            <form action="<?php echo BASE_DIR ?>quantriuser/SuaThongTinNhanVien" method="POST" >
                <div class="col-lg-6 col-md-6 " >
                    <div class="form-group" >
                        Username
                        <input required="required" name="username" value="<?php echo $NVHienTaiXem->usrname ?>" class="form-control" >
                    </div>
                    <div class="form-group" >
                        Nhóm
                        <select name="Nhom" required="required" class="form-control"  >
                            <?php
                            $ListNhom = $Model_QuangTri->getListNhom();
                            foreach ($ListNhom as $k => $Nhom) {
                                if ($k > $NVHienTai['Nhom']) {
                                    ?>
                                    <option   value="<?php echo $k ?>" ><?php echo $Nhom ?></option>
                                    <?php
                                }
                            }
                            ?>
                        </select>
                    </div>
                    <div class="form-group" >
                        Email
                        <input name="email" required="required" value="<?php echo $NVHienTaiXem->email ?>" class="form-control" >
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 " >
                    <div class="form-group" >
                        Họ Tên
                        <input name="HoTen" required="required" value="<?php echo $NVHienTaiXem->HoTen ?>" class="form-control" >
                    </div>
                    <div class="form-group" >
                        Địa Chỉ
                        <textarea name="DiaChi" required="required"  class="form-control" ><?php echo $NVHienTaiXem->DiaChi ?></textarea>
                    </div>
                    <div class="form-group" >
                        Số Điện Thoại
                        <input name="SDT" required="required" value="<?php echo $NVHienTaiXem->SDT ?>"  type="text" class="form-control" >
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 text-center "  >
                    <div class=" form-group" >
                        <input name="Sua" type="submit" value="Sửa usename" class="btn btn-success" >
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-4 col-md-4 " >
            <div class="panel panel-default" >
                <div class="panel-heading" >
                    <h3 class="panel-title" >
                        reset password cho tài khoản: <?php echo $NVHienTaiXem->usrname; ?>
                    </h3>
                </div>
                <div class="panel-body" >
                    <form method="POST" action="<?php echo BASE_DIR ?>quantriuser/resetpassword" >
                        <div class="form-group">
                            <label>Mật Khẩu</label>
                            <input name="password" type="text" value="" class="form-control"  >
                        </div>
                        <div class="form-group">
                            <label>&nbsp;</label>
                            <input value="Sửa Mật Khẩu" type="submit" name="SuaPassword" class="btn btn-success btn-block sua" /> 
                            <input value="<?php echo $NVHienTaiXem->usrname ?>" type="hidden" name="username" /> 
                        </div>
                    </form>
                </div>
            </div>


        </div>

    </div>
</div>